author: Mykindos
main: net.betterpvp.clans.Clans
name: Clans
startup: postworld
version: '1.0'
depend: [Core, ProtocolLib, Cartographer2]
api-version: 1.15
commands:
  clan:
    description: Base command for all clan related things
    aliases: [c, f, faction, clans]
  kit:
  build:
  coords:
  scan:
  craft:
  hub:
  